# netlify.toml

# Global settings applied to the whole site.
# “build” is a required context for Netlify since it’s where the build commands are stored.
[build]
    base = "StockMatch/frontend/"
    publish = "StockMatch/frontend/build/"
    command = "CI='' npm run build"

# Redirects all requests to the main index.html where the React app is mounted.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensures that the redirect will take precedence over existing files.

# If you have any headers to set in HTTP responses, you can use this section.
#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
