# netlify.toml

# Global settings applied to the whole site.
# “build” is a required context for Netlify since it’s where the build commands are stored.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "/"

  # The command to run to build the site.
  command = "CI= npm run build"
  # The directory to publish (relative to the root of your repo).
  # This will contain your built site.
  publish = "build/"

# Redirects all requests to the main index.html where the React app is mounted.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensures that the redirect will take precedence over existing files.

# If you have any headers to set in HTTP responses, you can use this section.
#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
